services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  licencias:
    build: ../Licenses-Service
    container_name: licencias_service
    restart: on-failure
    environment:
          POSTGRES_HOST: db
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: user
          POSTGRES_PASSWORD: password
          POSTGRES_NAME: health
          POSTGRES_SSLMODE: disable
          POSTGRES_TIMEZONE: America/Santiago
          POSTGRES_URL: postgres://user:password@db:5432/health?sslmode=disable
          PORT: 8081
          HOST: 0.0.0.0
          DB_MAX_IDLE_CONNS: 10
          DB_MAX_OPEN_CONNS: 100
          DB_CONN_MAX_LIFETIME: 3600
          APP_ENV: development
          LOG_LEVEL: info
          GORM_LOG_LEVEL: info
          GORM_SLOW_THRESHOLD: 200
    ports:
      - "8081:8081"
    depends_on:
      - db

  portal-paciente:
    build: ../Patient-Service
    container_name: portal_service
    environment:
      LICENSES_URL: http://licencias:8081
    ports:
      - "8082:8082"
    depends_on:
      - licencias

  validador-aseguradora:
    build: ../Insurance-Service
    container_name: validador_service
    environment:
      LICENSES_URL: http://licencias:8081
    ports:
      - "8083:8080"
    depends_on:
      - licencias
